name: feature request
description: Request a new Feature you would like to see in our product.
labels: ["🍎 core team", "📚 spike"]

body:
  - type: markdown
    attributes:
      value: |
        ## Prerequisites
        Please guarantee that you have followed these steps as they help us triage new Feature requests for what needs to be added to the backlog.

        - [ ] I have checked the existing Issues for a duplicate of this Feature
        - [ ] I have checked the roadmap in the documentation and did not find this Feature there
        - [ ] The Feature I'm requesting has come from direct user feedback (mine or someone elses)

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Explain in a few lines how the user would expect to interact with this new feature.
      placeholder: "i.e.: when the user ... they should be able to ... so that ..."
    validations:
      required: true
