blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/Mrh5NYw52S
    about: |
      If you want to reach the development community but cannot find an appropriate
      template for your question, you can join our discord server and share questions
      new learnings or requests there 💬