name: Move new issues into Project Boards
on:
  issues:
    types: [assigned]
jobs:
  move-issue-to-repository-project-column:
    name: Move issues to repository project column
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to 'To do' column if body has a mark 'issue:todo'
        uses: fojia/action-move-issues-to-column@master
        with:
          project: "test_project"
          column: "In Progress"
          owner: "camelPhonso"
          repo: ".github"
          type: "repo"
          github_token: ${{ secrets.GITHUB_TOKEN }}
