name: Move new issues into In Progress
on:
  issues:
    types: [assigned]
jobs:
  move-issue-to-repository-project-column:
    name: Move issues to repository project column
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to 'In Progress'
        uses: kin/gh-action-move-issues-to-column@v1.0
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          project-name: "test_project"
          target-column: "In Progress"
