name: Move new issues into backlog
on:
  issues:
    types: [unassigned]
jobs:
  move-issue-to-repository-project-column:
    name: Move issues to repository project column
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to 'Backlog'
        uses: kin/gh-action-move-issues-to-column@v1.0
        with:
          project-name: "test_project"
          target-column: "Backlog"
          access-token: ${{ secrets.GITHUB_TOKEN }}
