name: Move new issues into backlog
on:
  issues:
    types: [unassigned]
jobs:
  move-issue-to-repository-project-column:
    name: Move issues to repository project column
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to 'Backlog'
        uses: fojia/action-move-issues-to-column@master
        with:
          project: "test_project"
          column: "Backlog"
          owner: "enBloc-org"
          repo: ".github"
          type: "repo"
          github_token: ${{ secrets.GITHUB_TOKEN }}
