name: Move new issues into in progress
on:
  issues:
    types: [assigned]
jobs:
  move-issue-to-repository-project-column:
    name: Move issues to repository project column
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to 'In Progress'
        uses: fojia/action-move-issues-to-column@master
        with:
          project: "test_project"
          column: "In Progress"
          owner: "enBloc-org"
          repo: ".github"
          type: "org"
          github_token: ${{ secrets.GITHUB_TOKEN }}
