name: Move unassigned Issues to the Backlog

on: 
  issues:
    types: [unassigned]

jobs:
  move-issue-to-backlog:
    runs-on: ubuntu-latest

    steps:
      - name: Move unassigned issue to backlog
        id: move_issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const project_id = 6; // Replace with your actual project ID
            const column_name = 'Backlog';

            // Get the project columns
            const projectColumns = await github.rest.projects.listColumns({
              project_id: project_id
            });

            const backlogColumn = projectColumns.data.find(column => column.name === column_name);
            if (!backlogColumn) {
              throw new Error(`Could not find column: ${column_name}`);
            }

            // Add the issue to the project column
            await github.rest.projects.createCard({
              column_id: backlogColumn.id,
              content_id: context.issue.node_id,
              content_type: 'Issue'
            });

            core.info(`Moved issue #${issue_number} to column ${column_name}`);
